pip install git+https://github.com/fe1ixxu/ALMA.git@alma-r-hf
pip install peft==0.5.0
pip install sentencepiece
pip install sacrebleu
pip install ipython
pip install datasets
pip install evaluate
pip3 install deepspeed==0.13.1
pip install einops
pip install wandb
pip install zstandard
pip install accelerate==0.27.2
pip install jsonlines
pip install trl
pip install unbabel-comet
